export const IMAGE = {
  avatarMan: '/images/default_avatar_man.png',
  liveStream: '/images/live_stream.png',
  imageVideo: '/images/image_video.png',
  emoji: '/images/emoji.png',
  publicStatus: '/images/public.png',
  addImage: '/images/add-image.png',
  minus: '/images/minus.png',
  hahaEmoji: '/images/haha-emoji.png',
  likeEmoji: '/images/like-emoji.png',
  comment: '/images/comment.png',
  share: '/images/share.png',
  likeGif: '/images/like-gif.gif',
  loveGif: '/images/love-gif.gif',
  careGif: '/images/care-gif.gif',
  hahaGif: '/images/haha-gif.gif',
  wowGif: '/images/wow-gif.gif',
  sadGif: '/images/sad-gif.gif',
  angryGif: '/images/angry-gif.gif',
  friend: '/images/friend.png',
  group: '/images/group.png',
  saved: '/images/saved.png',
  memorie: '/images/memorie.png',
  video: '/images/video.png',
  adCenter: '/images/adCenter.png',
  adManager: '/images/adManager.png',
  blood: '/images/blood.png',
  climate: '/images/climate.png',
  crisis: '/images/crisis.png',
  event: '/images/event.png',
  feed: '/images/feed.png',
  fundraiser: '/images/fundraiser.png',
  gamingVideo: '/images/gamingVideo.png',
  marketPlace: '/images/marketPlace.png',
  messenger: '/images/messenger.png',
  messengerKid: '/images/messengerKid.png',
  playGame: '/images/playGame.png',
  recentAdActivity: '/images/recentAdActivity.png',
  savePost: '/images/post/save.png',
  notificationsPost: '/images/post/notificatioins.png',
  editPost: '/images/post/edit.png',
  trashPost: '/images/post/trash.png',
  settingHeader: '/images/header/setting.png',
  supportHeader: '/images/header/support.png',
  displayHeader: '/images/header/display.png',
  feedbackHeader: '/images/header/feedback.png',
  logOutHeader: '/images/header/logOut.png',
  cameraProfile: '/images/profile/camera.png',
  testImg: '/images/test-img.jpg',

  edit: '/images/edit.png',
  delete: '/images/delete.png',
}

export const IMAGE_SIZE = {
  MIN_SIZE: 50 * 1024, // 50 kb
  MAX_SIZE: 5 * 1024 * 1024, // 5MB
}
